# Site Settings
title: Ted | A blog for myself
email: greenbluebit@gmail.com
description: Place for me to show my work and maybe have a rant or two.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://greenbluebit.github.io" # the base hostname & protocol for your site
google_analytics: "UA-117810967-1"

# User Settings
username: Ted
user_description: Software developer in Denmark, really into games, AI and DIY electronics.
disqus_username: disqus_NyvU8I387a

# Social Media
# Remove the item if you don't need it
github_username: greenbluebit
facebook_username: ted.blop
twitter_username: theodor_purcaru
instagram_username: tedblop
linkedin_username: theodorpurcaru
medium_username: greenbluebit

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
