# Site settings
title: Theodor Purcaru
email: greenbluebit@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am awesome,
  Agile & Sexy. Hire Me
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for site, e.g. http://example.com
meta_author: Purcaru Theodor
keywords: "your keywords, separated by commas"
# Google webmaster tools
#google_verify:


# Color settings
color:
  cold-dark: 2b2f3d
  cold-light: 466874
  warm-dark: 4f4e47
  warm-light: 9f926e
  off-white: f7f7e2

# Collections
collections_dir: collections
collections:
  - skills
  - jobs
  - qualifications
  - projects

# Social networks
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
