# Site settings
title: Theodor Purcaru
email: greenbluebit@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Developer.
  Looking for projects to sink my teeth in.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
meta_author: Theodor Purcaru
keywords: "software developer, programming, game development"
# Google webmaster tools
#google_verify:
# Color settings
color:
  cold-dark: 2b2f3d
  cold-light: 466874
  warm-dark: 4f4e47
  warm-light: 9f926e
  off-white: f7f7e2

# Collections
collections_dir: collections
collections:
  - skills
  - jobs
  - education
  - projects

# Tags for projects
taggers:
  - title: Hobby
  - title: Work
  - title: Game-Jam
  - title: IoT
  - title: C#
  - title: Java
  - title: SQL
  - title: noSQL
  - title: Android
  - title: Bluetooth
  - title: C++
  - title: Unity
  - title: Angular
  - title: Frontend


# Social networks
social:
  - title: twitter
    url: https://twitter.com/theodor_purcaru
  - title: facebook
    url: https://www.facebook.com/ted.blop
  - title: stack-overflow
    url: https://stackoverflow.com/users/4284444/bbit
  - title: bitbucket
    url: https://bitbucket.org/Ted_Blop/
  - title: github
    url: https://github.com/greenbluebit

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
